spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      routes:
        - id: config_route
          predicates:
            - Path=/gateway/to-user/**
          filters:
            - StripPrefix=2 # 这样转发时就会去掉 从左往右两个参数/gateway/to-user
            - JimDefine=Hello Jim
          uri: http://localhost:8081/

        - id: lb_route
          predicates:
            - Path=/lb/**
          filters:
            - StripPrefix=1
          uri: lb://order-service
        - id: ratelimiter_route
          predicates:
            - Path=/ratelimiter/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                deny-empty-key: true
                keyResolver: '#{@ipAddressKeyResolver}'
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 2
          uri: lb://order-service
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  redis:
    host: r-wz9l1uaq7hbkntiin4pd.redis.rds.aliyuncs.com
    port: 6379
    password: RfyS8wJZCrM4
    database: 5

management:
  endpoints:
    web:
      exposure:
        include: "*"
